---
- name: Install and set up Redis
  hosts: webservers
  tasks:
    - name: Download Redis
      get_url:
        url: http://download.redis.io/redis-stable.tar.gz
        dest: /home/vagrant/redis-stable.tar.gz
    - name: install make
      become: true
      apt:
        name: make
        state: present
        update_cache: true
    - name: Install Redis-tools
      become: true
      apt:
        name: redis-tools
        state: present
    - name: Install Redis-server
      become: true
      apt:
        name: redis-server
        state: present
    - name: Install build esseitial
      become: true
      apt:
        name: build-essential
        state: present
    - name: Create target dir
      file:
        path: /home/vagrant/redis-stable
        state: directory
    - name: Extract Redis
      unarchive:
        src: /home/vagrant/redis-stable.tar.gz
        dest: /home/vagrant/redis-stable
        remote_src: true
    - name: Run make
      make:
        chdir: /home/vagrant/redis-stable/redis-stable/deps
        target: "{{ item }}"
      loop:
        - jemalloc
        - linenoise
        - lua
#        - geohash-int
    - name: run make install
      make:
        chdir: /home/vagrant/redis-stable/redis-stable
# TODO make paths configurable
