---
  - name: Create Destination directory for deploy
    become: true
    file:
      path: "{{ deploy_path }}"
      state: directory
  - name: set user and group
    become: true
    file:
      path: "{{ deploy_path }}"
      owner: {{file_owner}}
      group: {{group}}
  - name: Remove pre existing vendor directory
    file:
      path: "{{deploy_path}}/vendor"
      state: absent
    become: false
  - name: Deploy Symfony using git
    git:
      repo: {{git_repository}}
      dest: "{{ deploy_path }}"
      force: yes
      version: main
    become: false
  - name: Fix file permissions
    become: true
    file:
      recurse: yes
      path: "{{ deploy_path }}/var"
      owner: {{file_owner}}
      group: {{group}}
  - name: Run composer install
    shell: "composer install"
    args:
      chdir: "{{ deploy_path }}"
    become: false
  - name: "Restart NGINX"
    service:
      name: nginx
      state: restarted
    become: true

