---
- name: Update packages
  hosts: webservers
  become: true
  tasks:
    - name: Run apt-get update
      apt:
        update_cache: yes
    - name: Run apt-get upgrade
      apt:
        force_apt_get: yes
    - name: Run apt-get auto-remove
      apt:
        autoremove: yes
    - name: Run apt-get dist-upgrade
      apt:
        upgrade: dist
