---
- name:
  ansible.builtin.file:
    path: "{{ dest }}"
    state: directory
    mode: '0755'
- name: Pull the latest changes
  ansible.builtin.git:
    repo: "{{ repo }}"
    dest: "{{ dest }}"
    force: yes
    update: yes
    single_branch: yes
    version: main
    accept_hostkey: yes
