---
- name: "Create a simple LEMP stack webserver for Symfony 4"
  hosts: webservers
  become: true
  environment:
    APP_ENV: test
  tasks:
    - apt_repository:
        repo: ppa:ondrej/php
    - name: "Install packages"
      apt: name={{item}} state="present"
      with_items:
      - nginx
      - php7.2-fpm
      - php7.2-mysql
      - php7.2-xml
      - php7.2-cli
      - php-sqlite3
      - php7.2-mbstring
      - mysql-server
      - zip
      - unzip
      - php7.2-zip
    - name: Run apt-get update
      apt:
        update_cache: yes
    - name: Create temp directory for Composer
      file:
        path: /var/tmp/composer
        state: directory
    - name: Get Composer
      get_url:
        url: https://getcomposer.org/installer
        dest: /var/tmp/composer/composer-setup.php
    - name: Install composer
      shell: "php /var/tmp/composer/composer-setup.php --install-dir=/usr/local/bin --filename=composer"
    - name: Delete composer installer
      file:
        path: /var/tmp/composer/composer-setup.php
        state: absent
    - name: "Copy config file"
      copy: src=serverconfig dest=/etc/nginx/sites-available/default
    - name: "Restart NGINX"
      service: name=nginx state=restarted
