---
- name: "Create a simple LEMP stack webserver for Symfony 4"
  hosts: webservers
  tasks:
    - name: "Install packages"
      apt: name={{item}} state="present"
      become: true
      with_items:
      - nginx
      - php7.2-fpm
      - php7.2-mysql
      - php7.2-xml
      - php7.2-cli
      - mysql-server

    - name: "Copy config file"
      copy: src=serverconfig dest=/etc/nginx/sites-available/default
      become: true

    - name: "Restart NGINX"
      service: name=nginx state=restarted
      become: true
