---
- name: "Create a simple LEMP stack webserver for Symfony 4"
  hosts: webservers
  become: true
  tasks:
    - apt_repository:
        repo: ppa:ondrej/php
    - name: "Install packages"
      apt: name={{item}} state="present"
      with_items:
      - nginx
      - php7.2-fpm
      - php7.2-mysql
      - php7.2-xml
      - php7.2-cli
      - mysql-server
    - name: Run apt-get update
      apt:
        update_cache: yes
    - name: "Copy config file"
      copy: src=serverconfig dest=/etc/nginx/sites-available/default
    - name: "Restart NGINX"
      service: name=nginx state=restarted
