---
  - name: add repositories
    apt_repository:
      repo: ppa:ondrej/php
  - name: "Install packages"
    apt: name={{item}} state="present"
    with_items:
    - mysql-server
    - php-curl
    - php-sqlite3
    - php8.1-apcu
    - php8.1-cli
    - php8.1-fpm
    - php8.1-intl
    - php8.1-mbstring
    - php8.1-mysql
    - php8.1-xml
    - php8.1-zip
    - php8.1-sqlite3
    - unzip
    - zip
  - name: "get config for nginx"
    vars:
      error_log_location: "/var/log/nginx/project_error.log"
      access_log_location: "/var/log/nginx/project_access.log"
    include: partials/nginx.yml
  - name: Run apt-get update
    apt:
      update_cache: yes
  - name: Create temp directory for Composer
    file:
      path: /var/tmp/composer
      state: directory
  - name: Get Composer
    get_url:
      url: https://getcomposer.org/installer
      dest: /var/tmp/composer/composer-setup.php
  - name: Install composer
    shell: "php /var/tmp/composer/composer-setup.php --install-dir=/usr/local/bin --filename=composer"
  - name: Delete composer installer
    file:
      path: /var/tmp/composer/composer-setup.php
      state: absent
