---
- name: "Create a LEMP stack web server for Symfony 4"
  hosts: webservers
  become: true
  environment:
    APP_ENV: test
  vars_prompt:
    - name: "type"
      prompt: "Use nginx or apache as a web server"
      private: no
  tasks:
    - apt_repository:
        repo: ppa:ondrej/php
    - name: "Install packages"
      apt: name={{item}} state="present"
      with_items:
      - mysql-server
      - php-curl
      - php-sqlite3
      - php7.2-apcu
      - php7.2-cli
      - php7.2-fpm
      - php7.2-intl
      - php7.2-mbstring
      - php7.2-mysql
      - php7.2-xml
      - php7.2-zip
      - unzip
      - zip
    - name: Run apt-get update
      apt:
        update_cache: yes
    - name: Create temp directory for Composer
      file:
        path: /var/tmp/composer
        state: directory
    - name: Get Composer
      get_url:
        url: https://getcomposer.org/installer
        dest: /var/tmp/composer/composer-setup.php
    - name: Install composer
      shell: "php /var/tmp/composer/composer-setup.php --install-dir=/usr/local/bin --filename=composer"
    - name: Delete composer installer
      file:
        path: /var/tmp/composer/composer-setup.php
        state: absent

    - name: Fail if unexpected value choice for webserver
      fail:
        msg: "choose nginx or apache. Input was {{ type }}"
      when: type != "nginx" and type != "apache"

    - name: "Copy NGINX config file"
      when: type == "nginx"
      template:
        src: ../templates/serverconfig
        dest: /etc/nginx/sites-available/default
    - name: "Install the webserver"
      apt: name="{{ "nginx" if type == "nginx" else "apache2" }}" state="present"

    - name: "Restart Apache"
      service: name=apache2 state=restarted
      when: type == "apache"
    - name: "Restart NGINX"
      service: name=nginx state=restarted
      when: type == "nginx"
