---
- hosts: webservers
  name: Deploy Symfony
  environment:
    APP_ENV: test
  tasks:
    - name: Create Destination directory for deploy
      become: true
      file:
        path: /vagrant_dev
        state: directory
    - name: set user and group
      become: true
      file:
        path: /vagrant_dev
        owner: vagrant
        group: www-data
    - name: Remove pre existing vendor directory
      file:
        path: /vagrant_dev/vendor
        state: absent
    - name: Deploy Symfony using git
      git:
        repo: https://github.com/symfony/demo
        dest: /vagrant_dev
        force: yes
        version: master
    - name: Fix file permissions
      become: true
      file:
        recurse: yes
        path: /vagrant_dev/var
        owner: vagrant
        group: www-data
    - name: Run composer install
      shell: "composer install"
      args:
        chdir: /vagrant_dev
# This fails for some reason...
#    - name: Run composer install
#      composer:
#        command: install
#        working_dir: /vagrant_dev
