---
- hosts: webservers
  name: Deploy Symfony
  environment:
    APP_ENV: test
  tasks:
    - name: Create Destination directory for deploy
      become: true
      file:
        path: "{{ deploy_path }}"
        state: directory
    - name: set user and group
      become: true
      file:
        path: "{{ deploy_path }}"
        owner: vagrant
        group: www-data
    - name: Remove pre existing vendor directory
      file:
        path: "{{deploy_path}}/vendor"
        state: absent
    - name: Deploy Symfony using git
      git:
        repo: https://github.com/symfony/demo
        dest: "{{ deploy_path }}"
        force: yes
        version: master
    - name: Fix file permissions
      become: true
      file:
        recurse: yes
        path: "{{ deploy_path }}/var"
        owner: vagrant
        group: www-data
    - name: Run composer install
      shell: "composer install"
      args:
        chdir: "{{ deploy_path }}"
    - name: "Restart Apache"
      service:
        name: nginx
        state: restarted
      become: true
# This fails for some reason...
#    - name: Run composer install
#      composer:
#        command: install
#        working_dir: /vagrant_dev
