---
- name: Install and set up Memcached
  hosts: webservers
  become: true
  tasks:
    - name: Install Memcached
      apt:
        update_cache: true
        name: memcached
        state: present
    - name: Install memcached tools
      apt:
        name: libmemcached-tools
        state: present
